<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employer State</name>
   <tag></tag>
   <elementGuidId>d8c2685c-d9a1-4994-9cc0-d36d25e21027</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.form-control.ui.fluid.selection.dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Employer State')]/following-sibling::div[@aria-haspopup='true']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6db79585-4cfe-4d31-ad67-578cc3111017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui fluid selection dropdown</value>
      <webElementGuid>c94118ae-ee5b-4bd9-bc1f-52c02b89510a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>451c2682-032a-48ad-b5eb-80ef70532a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>241ff233-60a3-4f17-8441-0eec415ab05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eqkka6n&quot;)/div[@class=&quot;choices form-group formio-choices&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]</value>
      <webElementGuid>e2876dbf-5d52-4e3a-821a-3eb021b41778</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eqkka6n']/div/div</value>
      <webElementGuid>0af05e31-f1c2-4af9-91ca-5c95394936ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer State'])[1]/following::div[2]</value>
      <webElementGuid>72d6dd72-17e6-46b6-9d0f-70a473499ca9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer City'])[1]/following::div[6]</value>
      <webElementGuid>7edebfc4-cd1b-448a-a657-2dca331e6235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No choices to choose from'])[1]/preceding::div[2]</value>
      <webElementGuid>d8c2ead2-b26b-41b1-be87-a1f8fd458738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employer Zip'])[1]/preceding::div[6]</value>
      <webElementGuid>9b903e41-6a9e-41e6-9f21-b11d2994dc39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div</value>
      <webElementGuid>9868c02b-f308-4f7c-abea-5ba2f7653219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
