<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_employerIncorpDate-year</name>
   <tag></tag>
   <elementGuidId>07f370c8-4ede-49bf-b063-5ccbe140e0d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employerIncorpDate-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employerIncorpDate-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0f9bd161-5c6b-47ea-a6a2-ff00ce562b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>355930d5-4e23-4ca8-a109-1b7190eb4205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-efp5hvo-employerIncorpDate</value>
      <webElementGuid>1cc37152-c6b4-4667-bb3d-21d1d3879ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2030</value>
      <webElementGuid>1602a19b-bf28-48c7-a889-9c72740c29fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>192e8e97-1022-4909-a919-9ff57f99f48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9e957195-ccf4-4a00-ad9a-a6edfce77137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8dcef31a-ec58-454a-9434-88cb68d3227a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formio-day-component-year</value>
      <webElementGuid>cd0077ab-8e8f-4324-af4a-dc1b69d48143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employerIncorpDate-year</value>
      <webElementGuid>22140e90-4030-4b1f-9e58-ab948768282a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>b1afc017-0fcf-4837-b6ae-eeffc09496be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dada731b-be5c-4ece-b863-c704e13b0259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employerIncorpDate-year&quot;)</value>
      <webElementGuid>76053bb9-8320-4345-beff-2ff997e03e17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employerIncorpDate-year']</value>
      <webElementGuid>dab3a64f-e8ba-4e39-8bbf-0b32332ed227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='efp5hvo']/div/div[3]/div/input</value>
      <webElementGuid>3186184d-1acd-4804-9392-6ee4f7645ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>df85af01-1869-4035-9da6-070eade4ebf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'employerIncorpDate-year']</value>
      <webElementGuid>309b5380-5268-414d-822b-59f3f8f98b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
