<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employer Address</name>
   <tag></tag>
   <elementGuidId>6d57e6a1-a736-4b57-b9e7-f218156a7839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enx96h-employerAddress01</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Employer Address')]/following-sibling::div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>19d16dfc-9e54-471c-917f-7a5026066f30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69b1b3c6-e2ed-445c-8f64-34042868f372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-enx96h-employerAddress01</value>
      <webElementGuid>3bffcea2-ea22-49e2-b734-37c384e59e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enx96h-employerAddress01</value>
      <webElementGuid>c0095af3-f7d9-46b9-aad0-3c85ec52281c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6b63ecc6-9a8e-432f-bda1-743e1e667b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>dd3f291d-b222-4f8f-b969-41b6c557cd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>1abeb6f0-d4c1-4355-b089-e94661d2828a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5ecc7d7-1750-4bd4-b266-2b88b935d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[employerAddress01]</value>
      <webElementGuid>1e2505d0-d2af-4c72-84c6-4d273994449a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7fde422-6760-4d35-8fb9-1020451be189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8ad32caf-ba82-4288-b914-b952be9733ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enx96h-employerAddress01&quot;)</value>
      <webElementGuid>b88fd9bb-6bed-4c9b-80ff-58359034da52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='enx96h-employerAddress01']</value>
      <webElementGuid>e0665b77-bfce-4fd2-9d3e-603e08169241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='enx96h']/div/input</value>
      <webElementGuid>da499b49-d9d4-48a9-8e80-340d678d1e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>eb87c058-1f95-449f-9219-5f81afaf0380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'enx96h-employerAddress01' and @type = 'text' and @name = 'data[employerAddress01]']</value>
      <webElementGuid>a7c459d7-c488-49f0-abb1-5ccf510b2168</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
