<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employer Email</name>
   <tag></tag>
   <elementGuidId>0cdaa5d7-8998-4742-9b11-26085d18fa8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eaz0g7h-employerEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Employer Email')]/following-sibling::div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b9d0ebf-179c-4244-b470-cc5759abb9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>37c1e833-bb6c-46c6-99b3-6054e1bc2aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-eaz0g7h-employerEmail</value>
      <webElementGuid>6e32b3e8-84cc-4eab-bea4-80145c703edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eaz0g7h-employerEmail</value>
      <webElementGuid>42b8d9bd-cf53-4bb8-abfe-7f24f767d7ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>179898e4-29a2-42a4-8c96-a8f1e9a785e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>d47cd7f0-95c2-4d04-a5ab-17a67156459b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4b9cb183-321a-40ba-b5c2-8886255112de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>c1825234-9b2f-4f45-adfd-84afbb421afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[employerEmail]</value>
      <webElementGuid>140be8ac-b0ae-46ff-84e8-26aa3fd9a2cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>894d0b34-04e9-478f-b20c-a7339e1cd7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>40d34459-78ae-4b9f-8625-9382c5a2cf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eaz0g7h-employerEmail&quot;)</value>
      <webElementGuid>23f7a3b9-ce19-4153-83a4-0747e46744eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eaz0g7h-employerEmail']</value>
      <webElementGuid>033c159e-c50f-4e0b-b928-bb2f14d87f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eaz0g7h']/div/input</value>
      <webElementGuid>efb349eb-7cd8-48b0-a3b8-72bc4fa9365e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>6b80eb8c-321b-4273-a65c-1d881387f6b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eaz0g7h-employerEmail' and @type = 'email' and @name = 'data[employerEmail]']</value>
      <webElementGuid>601aad89-3619-449d-9231-5e44282ba6c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
