<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Day_employerIncorpDate-day</name>
   <tag></tag>
   <elementGuidId>7aab241b-833b-469f-97bd-c6c55e14af01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#employerIncorpDate-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='employerIncorpDate-day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48d55d9b-c11e-4029-85bf-4d4440ef5c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eec1a1c6-e78c-4ba4-92f5-01770a415267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-efp5hvo-employerIncorpDate</value>
      <webElementGuid>fe67b0cf-15d2-4f77-bdd2-13b097219947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>d21c9940-b538-4b5e-adf1-e90a60ad0ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a7fb241e-fd82-4e61-89f6-fd3bb844d029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>445e6846-a4bb-4550-b497-3acb9c4750a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>80e50d8c-bcb0-4720-b2b2-1ec62d52c6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formio-day-component-day</value>
      <webElementGuid>1395d17d-f84d-436e-9144-fbc664ce5d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>employerIncorpDate-day</value>
      <webElementGuid>fb9d3496-fc26-4f6b-83a2-f65a47a38f27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>614470a3-ed9a-4798-8a78-c465553b6b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7ad52c1-792d-459e-b7e9-8c47e2f309ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;employerIncorpDate-day&quot;)</value>
      <webElementGuid>6660cd73-0f5d-4467-9377-d10b2c20255b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='employerIncorpDate-day']</value>
      <webElementGuid>2caa7766-f0c5-4992-8216-296a69c59ac6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='efp5hvo']/div/div[2]/div/input</value>
      <webElementGuid>1fc39d6f-746c-49b9-84e8-56c8a1bade29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>a711249e-6bc5-4909-9ec6-2f74d3095ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'employerIncorpDate-day']</value>
      <webElementGuid>22090b4a-36e7-4de7-8fcf-6a3023c7164b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
