<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employer EIN</name>
   <tag></tag>
   <elementGuidId>6fe2e145-f1ce-4bf6-8bd7-810d92562065</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ektx978-employerEin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Employer EIN')]/following-sibling::div//input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34c6de02-660f-4a0d-be6d-151040e23bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c854f0bf-d7f1-42c5-a228-4a974f1790e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-ektx978-employerEin</value>
      <webElementGuid>99f8e36c-11b9-40fd-a865-7b427add76de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ektx978-employerEin</value>
      <webElementGuid>7c5bc435-2d7a-41bc-a2c0-153faae1d602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>815a788a-6d7b-4b73-aa5f-ab0f92e04bc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>19d973fa-b579-47b2-b7a0-d4435e6723d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>fe96690c-bc93-4625-a039-5db22e15e86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5a4f4467-fc58-49f3-b365-9407bee4452d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[employerEin]</value>
      <webElementGuid>4d11d7d9-401c-451c-a85c-3b4f657cfc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>26a5a8fc-d6a7-401d-ac24-710ae9fe1cb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__-_______</value>
      <webElementGuid>e5d2f612-6235-454e-90bb-89702284962f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff34d48e-37d7-4782-8770-3d6a2983008b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ektx978-employerEin&quot;)</value>
      <webElementGuid>e5df13a2-a42f-428d-ac97-528cb7aa33ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ektx978-employerEin']</value>
      <webElementGuid>2f41b062-f767-4653-a109-c2f2342ba1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ektx978']/div/input</value>
      <webElementGuid>d631868e-4c91-4a70-aa40-24dc92725f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>4af5f2aa-1d9e-4978-baa8-20cb1353d71d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ektx978-employerEin' and @type = 'text' and @name = 'data[employerEin]' and @placeholder = '__-_______']</value>
      <webElementGuid>6b474208-0d38-499b-b245-163c271a4c5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
