<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Employer SuiteUnit Number</name>
   <tag></tag>
   <elementGuidId>08535c8a-0f18-4273-a7b6-fc815b3d105e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ena7e6o-employerAddress02</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Employer Suite')]/following-sibling::div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ed426c9-499a-437b-bde8-4f8214f9a0a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>83663d6b-326f-4591-8a3d-d0113090a4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-ena7e6o-employerAddress02</value>
      <webElementGuid>04a196db-5779-43ae-bcdc-47782906efd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ena7e6o-employerAddress02</value>
      <webElementGuid>86f66539-6b95-4728-8bcf-ac3cd486980a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d27738d1-6730-4edd-b0b2-7b91705ca54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>5199d129-bbcc-49d4-a31c-87c736016eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>6b4da1e2-9de5-4575-866f-3f57773efc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a406c6d3-fcb9-4f74-959b-f9f4fa1f94b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[employerAddress02]</value>
      <webElementGuid>f50f91c9-d3e0-4bff-be55-95e29790de61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be4b0604-06de-43d4-b31a-899f03ebd857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a9b0e08-fdd7-426d-8e57-4f10235312ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ena7e6o-employerAddress02&quot;)</value>
      <webElementGuid>0538ce1e-b946-4660-8ad8-a771cffd8eef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ena7e6o-employerAddress02']</value>
      <webElementGuid>3a2d2669-4108-4bed-952d-91c667307779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ena7e6o']/div/input</value>
      <webElementGuid>abb73d07-c1c1-426f-b6df-9e22b86a806e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>6c8c44ca-f7be-41ef-b2ae-b7fb87b185dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ena7e6o-employerAddress02' and @type = 'text' and @name = 'data[employerAddress02]']</value>
      <webElementGuid>b5ca36fb-0600-4400-93f5-56bb21575947</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
