<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_State of Incorporation</name>
   <tag></tag>
   <elementGuidId>407bb03c-d384-4beb-a4ae-1fab9df2a0b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e8790dj-employerStateFiled</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'State of Incorporation')]//following-sibling::div//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>83758fe9-cf28-447c-b7f4-8830f1e72556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4419ec8c-76b1-451b-9a36-23fe0be00218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e8790dj-employerStateFiled</value>
      <webElementGuid>fe99699c-3b0f-4910-960f-d26f0539da27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>4e2f02dc-6a46-49a1-a3f0-b0b58d289195</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>131a3ebd-395c-4d85-b287-5b6e9e5cc8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eafd67cd-625f-45d2-aa92-a32944720891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[employerStateFiled]</value>
      <webElementGuid>fb2915ef-2815-4964-b4ef-d96cf48ec8ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>f236615b-7b65-4c09-a5b6-33af5c1dc522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>29e775fa-9b81-4a41-833a-f1f5edd2fe77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>31aef62f-cb65-4096-8a0e-a20099640fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>9492c6cb-9cde-4191-947b-7d66fc3fed19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>Texas&lt;/span></value>
      <webElementGuid>998cc917-fd39-465d-931e-59461fd53428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e8790dj-employerStateFiled&quot;)</value>
      <webElementGuid>d3fb69cc-49b0-48b8-9af8-7de48bb6372e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e8790dj-employerStateFiled']</value>
      <webElementGuid>937a8c27-57db-48fb-9ac8-335028f5e6a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e8790dj']/div/div/select</value>
      <webElementGuid>d4900d98-51bd-48ca-be01-cae0b7f86e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State of Incorporation'])[1]/following::select[1]</value>
      <webElementGuid>e9c80e14-be90-4687-ba06-f120f98cc1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/following::select[1]</value>
      <webElementGuid>d2b2d25e-bed9-462b-bfeb-194bfdd72be0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Texas'])[3]/preceding::select[1]</value>
      <webElementGuid>521e4373-4db6-4a2c-912e-6b331ab1b1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[2]/preceding::select[1]</value>
      <webElementGuid>149b05d0-9773-45f7-9fac-e17ef09fc4d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>32b5996e-4f9f-4293-a24d-3e58da14e9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e8790dj-employerStateFiled' and @type = 'text' and @name = 'data[employerStateFiled]' and (text() = '&lt;span>Texas&lt;/span>' or . = '&lt;span>Texas&lt;/span>')]</value>
      <webElementGuid>4e8a31fc-1511-4046-bbac-41aa83165e5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
