<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_planSignature_signature-pad-canvas</name>
   <tag></tag>
   <elementGuidId>19f87ca1-0917-466e-828c-67d3d6d1c3ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e91c8tae']/div/div/canvas</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.signature-pad-canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>8cff938c-bdc2-4559-baa1-f8b7d1bf5f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>3499a1db-72d5-4b12-a537-067ad8b80883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>82a1a8d7-a1d1-4fe8-b0f2-1adf0c8d063b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>signature-pad-canvas</value>
      <webElementGuid>e5e7c66d-7146-4421-8c3e-697727b3f541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>858</value>
      <webElementGuid>565388c7-d6c4-45c1-a436-a9bafe579dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e91c8tae&quot;)/div[1]/div[@class=&quot;signature-pad-body&quot;]/canvas[@class=&quot;signature-pad-canvas&quot;]</value>
      <webElementGuid>25c000e2-c63b-45f5-89bc-721732b71149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e91c8tae']/div/div/canvas</value>
      <webElementGuid>c2a211f0-6a31-4d47-8f16-7f7ac62e8a29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>bd0a33b1-694a-4050-a17f-c5f527ed86da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
