<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_, numeric only,_col-md-6    col-md-offs_7b60c8</name>
   <tag></tag>
   <elementGuidId>b3abec58-b527-4b34-bbe5-a9fea35be3dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='em6ipz6']/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-6.col-md-offset-0.col-md-push-0.col-md-pull-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20967f76-a12c-45c0-8638-442367ac0f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>column-em6ipz6</value>
      <webElementGuid>97b660ca-417f-4d20-8444-2f55ab472f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-md-6
    col-md-offset-0
    col-md-push-0
    col-md-pull-0</value>
      <webElementGuid>6512c779-3998-4e52-b841-30e5e9e82e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;em6ipz6&quot;)/div[@class=&quot;col-md-6
    col-md-offset-0
    col-md-push-0
    col-md-pull-0&quot;]</value>
      <webElementGuid>9139580d-44b1-4f37-81cb-07468e46c2ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='em6ipz6']/div[2]</value>
      <webElementGuid>73d86a5f-408c-478d-9e80-286a59d51993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', numeric only,'])[1]/following::div[3]</value>
      <webElementGuid>0cfb0d4e-5c8a-4ebc-954f-c18cb3360745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB_trustAccountMonthlyActivityDomestic'])[1]/preceding::div[5]</value>
      <webElementGuid>38732f28-cd1c-4bb8-a591-218d5c768e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0-$25,000'])[1]/preceding::div[7]</value>
      <webElementGuid>1ca1f768-700f-43da-a463-4e374fa0b089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>da2da227-94f4-4a8d-a8aa-4e5aa6f56c77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
