<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TB_trustAccountMonthlyActivityDomestic__33c879</name>
   <tag></tag>
   <elementGuidId>b2541d2b-a129-4e7d-836b-2bebdca68097</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e08qq5h']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-control.ui.fluid.selection.dropdown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>490f8eb9-424f-42f3-8987-11e417020f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui fluid selection dropdown</value>
      <webElementGuid>f1227850-5512-4075-8df8-c3b93f00daee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6d7b2136-2beb-4803-9240-e75141367afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed57e59d-d9ae-447a-9386-f8d0df3bce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e08qq5h&quot;)/div[@class=&quot;choices form-group formio-choices&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]</value>
      <webElementGuid>ee731aee-72c7-4dd4-afa1-ac051a39f662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e08qq5h']/div/div</value>
      <webElementGuid>525ecd29-09ee-4a6f-b326-8790b542ea84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB_trustAccountMonthlyActivityDomestic'])[1]/following::div[2]</value>
      <webElementGuid>50911006-bc33-42fb-adb1-16f93d3187e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', numeric only,'])[1]/following::div[15]</value>
      <webElementGuid>082c2dda-884c-47ec-93e5-b1ea7e1a3965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0-$25,000'])[1]/preceding::div[2]</value>
      <webElementGuid>d97f00fe-9a73-4569-b26b-4d97935ab6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$25,000 to $100,000'])[1]/preceding::div[3]</value>
      <webElementGuid>34f6e600-b1f5-4e3c-9616-634e9da33800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>66391619-8da3-4ade-903f-a7cd24f7fcc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
