<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_2021 Tax YearRemove item</name>
   <tag></tag>
   <elementGuidId>6020b333-1d9c-4e60-b5a4-009ab600980d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='engzag']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.choices__item.choices__item--selectable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c50eb884-0bf3-4070-a66c-7e18a693ff3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--selectable</value>
      <webElementGuid>860e9d87-ccd4-47d4-8d8b-864ac24eb2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>b416f754-9f56-4425-99d1-16e90b1212c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>00/00/2021</value>
      <webElementGuid>b8575598-7829-4c47-8c86-bb243877eaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e069a97-e031-4feb-ae50-a5a9ce4042e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2021 Tax YearRemove item</value>
      <webElementGuid>91ea818b-1f60-4990-81a9-e36f2b87aec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;engzag&quot;)/div[@class=&quot;choices form-group formio-choices is-open is-focused&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]/div[@class=&quot;choices__list choices__list--single&quot;]/div[@class=&quot;choices__item choices__item--selectable&quot;]</value>
      <webElementGuid>60154171-4c10-4acc-86a9-9be7aa744ead</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='engzag']/div/div/div/div</value>
      <webElementGuid>fcf7833a-6b01-4950-ac90-2b5deb88a900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax Year Plan is Established'])[1]/following::div[4]</value>
      <webElementGuid>744df1bf-54b6-4aba-8b07-d7813c398d3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Before Submitting'])[1]/following::div[20]</value>
      <webElementGuid>52dec378-7607-4fdf-9dcf-c3b5327a2d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solo 401(k) Plan EIN'])[1]/preceding::div[6]</value>
      <webElementGuid>93815d87-331d-4aa6-93a6-4315c36fb2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>398e80e0-8094-4d8c-a42b-32701e641dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '2021 Tax YearRemove item' or . = '2021 Tax YearRemove item')]</value>
      <webElementGuid>11806bd5-7270-40db-94f4-68b5b6035429</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
