<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_State Issued_form-control ui fluid sele_3d5641</name>
   <tag></tag>
   <elementGuidId>a9ebfe1c-43ee-44c7-a7a0-e3d2418276bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eukj98 > div.choices.form-group.formio-choices > div.form-control.ui.fluid.selection.dropdown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='eukj98']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>de3e9b27-e8ca-4b01-a1fe-d9dae3f4b153</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ui fluid selection dropdown</value>
      <webElementGuid>f0c2c70e-ad66-4b3c-a76e-5c3e565021c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7be32372-56d5-4550-8af0-b2cd3ef65205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f9ba276c-466a-487a-a6d3-1ebb458711ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eukj98&quot;)/div[@class=&quot;choices form-group formio-choices&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]</value>
      <webElementGuid>bfb4b455-8b77-446f-a1b0-e7bb59484912</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eukj98']/div/div</value>
      <webElementGuid>6dd34f0c-420e-4b77-a79f-65ba2b6a38ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Issued'])[1]/following::div[2]</value>
      <webElementGuid>7499b836-953c-4476-9324-5df55ecd009f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Id Number'])[1]/following::div[6]</value>
      <webElementGuid>2af2e8d2-1b71-444e-a6bb-5b5efd01311e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No choices to choose from'])[1]/preceding::div[2]</value>
      <webElementGuid>ae1bf11d-b67c-4f09-ba5e-41188d4c3282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Expiration Date'])[1]/preceding::div[7]</value>
      <webElementGuid>c07edcc7-b2be-473a-a15c-694c5f6c6369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div</value>
      <webElementGuid>c2219073-b245-4729-94d0-e263ad8cc53e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
