<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Contact InformationFirst NameLast NameE_99fdfd</name>
   <tag></tag>
   <elementGuidId>912b6ec8-449d-4824-8dd0-e8a0e1bb0b96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex-grow.p-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>890a644f-f358-4c3b-b523-fa65c4629d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex-grow p-8</value>
      <webElementGuid>25c831ed-8b27-4eb1-aa66-46397e68a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Contact InformationFirst NameLast NameEmail AddressPhonePayment Information</value>
      <webElementGuid>5f56a8c5-ef40-4cd7-9a38-fbcbc3b42776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;max-w-screen-xl px-4 md:px-8 mx-auto mt-[120px]&quot;]/div[@class=&quot;flex rounded-lg border border-gray-200 shadow-md dark:border-gray-700 dark:bg-gray-800 flex-col bg-white p-4 mt-4 transition-opacity opacity-100&quot;]/div[@class=&quot;flex gap-12 items-stretch&quot;]/div[@class=&quot;flex-grow p-8&quot;]</value>
      <webElementGuid>f5c3592d-9650-4afc-8271-5f2f66027981</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/div[2]/div/div</value>
      <webElementGuid>2a1f1921-dd25-493e-a78a-7badc55f599c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finish Setting up Your Account'])[1]/following::div[3]</value>
      <webElementGuid>fd608f37-aa68-44b4-bd92-fd19b7b40382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[1]/following::div[4]</value>
      <webElementGuid>06d7be45-de14-4a41-8d01-b55eae804aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div</value>
      <webElementGuid>91570ec4-f359-4352-895f-353cb73ef399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Contact InformationFirst NameLast NameEmail AddressPhonePayment Information' or . = 'Contact InformationFirst NameLast NameEmail AddressPhonePayment Information')]</value>
      <webElementGuid>eb3b5fc9-a7e3-4d13-bb90-4f9af29cecf0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
