<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , hubspot-conversations-_2102a2</name>
   <tag></tag>
   <elementGuidId>1f46c4a7-cae3-488d-b167-981c3cd409b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hubspot-conversations-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='hubspot-conversations-iframe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62bd923a-5120-4f51-8f16-ab6ac55a48c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://app.hubspot.com/conversations-visitor/23684445/threads/utk/127178cdec8f44d397e722c9a6bf866f?uuid=6359a737481e4d0cbe4432433496553c&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=dev.sepirak.com&amp;inApp53=false&amp;messagesUtk=127178cdec8f44d397e722c9a6bf866f&amp;url=https%3A%2F%2Fdev.sepirak.com%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false</value>
      <webElementGuid>6470f239-5f34-4120-9fa5-cff48eae7ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hubspot-conversations-iframe</value>
      <webElementGuid>64707283-7c2b-4e7d-852b-5e901dadfe7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>region</value>
      <webElementGuid>2cb4bc5d-6cfb-4653-ae0c-6f0edda71f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Chat Widget</value>
      <webElementGuid>066c6738-ab44-4f66-a462-6fd58fc2ae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>chat-widget-iframe</value>
      <webElementGuid>f684806b-fc16-448a-a0e1-df03a2f67b9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hubspot-conversations-iframe&quot;)</value>
      <webElementGuid>806e17cb-96f4-4a11-9fe7-892c62f6063b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='hubspot-conversations-iframe']</value>
      <webElementGuid>aa5ae54e-e90d-4998-8e04-d58b5e930eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hubspot-messages-iframe-container']/iframe</value>
      <webElementGuid>92e6212a-2af2-4eae-a6a3-224268d186ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>d0f2c885-4e94-48d7-ae62-ddcd1630a380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://app.hubspot.com/conversations-visitor/23684445/threads/utk/127178cdec8f44d397e722c9a6bf866f?uuid=6359a737481e4d0cbe4432433496553c&amp;mobile=false&amp;mobileSafari=false&amp;hideWelcomeMessage=false&amp;hstc=null&amp;domain=dev.sepirak.com&amp;inApp53=false&amp;messagesUtk=127178cdec8f44d397e722c9a6bf866f&amp;url=https%3A%2F%2Fdev.sepirak.com%2F&amp;inline=false&amp;isFullscreen=false&amp;globalCookieOptOut=null&amp;isFirstVisitorSession=true&amp;isAttachmentDisabled=false&amp;enableWidgetCookieBanner=false&amp;isInCMS=false' and @id = 'hubspot-conversations-iframe']</value>
      <webElementGuid>8310e44b-b9a1-4a76-8707-673a7ea6d8d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
