<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Ssn_datatrusteeSsn</name>
   <tag></tag>
   <elementGuidId>82477e79-2aec-4e78-a5de-49c8b14c2f8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e3a8o737-trusteeSsn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e3a8o737-trusteeSsn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52d21c5d-ea7e-45d7-81c7-e9d4def9afb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa226d4d-a82b-454f-a198-1260a3a1abbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-e3a8o737-trusteeSsn</value>
      <webElementGuid>1ced337c-004a-4b6f-8b3b-27e4e1ac8445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e3a8o737-trusteeSsn</value>
      <webElementGuid>188b3296-11a3-4ecb-b821-f85d02ce6900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c5b647ae-7e37-45bd-98b7-6380e9785203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>3fc0db60-7d07-4252-a3cb-b9dee3743677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dc8a5f04-79cd-409f-82bc-7bf78fb78aea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>118a38a9-2801-432e-9e0a-0b1c541cbf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[trusteeSsn]</value>
      <webElementGuid>8d6fafa4-df29-4424-ad86-e5afb12ccaf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eb30a72-7c3a-414c-9001-e5e73f7dc749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>___-__-____</value>
      <webElementGuid>21b3f3db-32a6-46d1-88e2-eedfb1c2fd96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3a45807-c5d9-4729-9be2-3396dd535e6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e3a8o737-trusteeSsn&quot;)</value>
      <webElementGuid>e0103315-90a7-4a7e-9a9d-da991160aada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e3a8o737-trusteeSsn']</value>
      <webElementGuid>e078504e-9474-4cc0-9cff-1a97cd09ac54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e3a8o737']/div/input</value>
      <webElementGuid>c99a07ec-6a24-4ed2-a80e-73d10eb04df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/div/div/input</value>
      <webElementGuid>347e23a5-6568-4b8d-9f93-5ed8d51431dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e3a8o737-trusteeSsn' and @type = 'text' and @name = 'data[trusteeSsn]' and @placeholder = '___-__-____']</value>
      <webElementGuid>7c6bec29-406c-4cb8-90fd-aa69fde71e7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
