<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee Email_datatrusteeEmail</name>
   <tag></tag>
   <elementGuidId>9be1bf5e-1f6e-4db4-9820-042a4f8f208e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='eqiwdq-trusteeEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eqiwdq-trusteeEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f69bdc88-de22-483e-a2c7-26f0c690c075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7ea64d8e-40ba-4977-8f7c-a5d41e8874aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-eqiwdq-trusteeEmail</value>
      <webElementGuid>c9cadbfc-b413-446d-aa79-8f62bb830583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eqiwdq-trusteeEmail</value>
      <webElementGuid>4c35f2f5-1184-426f-8aed-d408fbe3584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8682101-0ed5-46de-8e1f-65aec20d13a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>dee4cc57-15f4-48e6-8842-9f17f2512af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c08975a1-8299-422e-8ce4-ebd8a8f8633e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>799f240c-1a13-42da-a806-b7ebe2f4e92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[trusteeEmail]</value>
      <webElementGuid>a345e641-7e2a-4fa1-9073-be2534b98228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ad2a086-3820-4666-b381-cbf121573e29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5566bf24-e911-4ab6-95bf-c79091c26bfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eqiwdq-trusteeEmail&quot;)</value>
      <webElementGuid>d3daeb0c-9838-4e14-ac76-de4be3f46f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='eqiwdq-trusteeEmail']</value>
      <webElementGuid>05174904-d49d-45ff-b090-146b9de95b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eqiwdq']/div/input</value>
      <webElementGuid>0442c61c-4976-4ec6-bd41-26e2ed6336ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>be846de1-284a-4c26-83ca-7a1f76c3625e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'eqiwdq-trusteeEmail' and @type = 'email' and @name = 'data[trusteeEmail]']</value>
      <webElementGuid>086db437-c795-410d-acdf-537a4f89a1e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
