<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_tbIdExpiryDate-year</name>
   <tag></tag>
   <elementGuidId>d52a28d7-67d1-467e-800a-3b4038d01cbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='tbIdExpiryDate-year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tbIdExpiryDate-year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87747726-2e52-419b-99e0-b3ae99c8bfb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18ffb790-1aa3-4e52-9352-410b5046676e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-e5l4v1h-tbIdExpiryDate</value>
      <webElementGuid>3f679f41-5228-4183-9c1c-f97937c93cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2030</value>
      <webElementGuid>19bcbce5-f3ca-44c7-a160-e96d9956bac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>8323fb76-cf00-429a-8588-079ddf7037da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>66c3fb28-eeac-4f5a-a579-f12a97dd9683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>288fbffc-f079-43ce-91fd-e07ec6b7c05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formio-day-component-year</value>
      <webElementGuid>d7889fe3-7d4a-4fb5-8b11-ff6edb1c9b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tbIdExpiryDate-year</value>
      <webElementGuid>d7d6f917-6256-43f2-96fb-25741d3290ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>83cfb34c-b612-49fa-a912-53c207828928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d65d96ed-e8bc-4401-a3c6-ce8baf86b273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbIdExpiryDate-year&quot;)</value>
      <webElementGuid>d930e532-583b-43f6-8698-601496ea62b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='tbIdExpiryDate-year']</value>
      <webElementGuid>9c5df842-8823-44f3-a0d6-0314be12cdaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e5l4v1h']/div/div[3]/div/input</value>
      <webElementGuid>3c36a3f9-50f5-4536-ace0-4551d5a80f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/div/input</value>
      <webElementGuid>775a5569-b7fc-4626-ab8d-3f2f0b33defa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'tbIdExpiryDate-year']</value>
      <webElementGuid>3c36ecdf-1b39-4eef-8fe0-e97f360de038</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
