<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Photo Id Number_datatbPhotoIdNumber</name>
   <tag></tag>
   <elementGuidId>283846b7-0127-43df-bb5c-0309a196de63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='e7h1j6-tbPhotoIdNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e7h1j6-tbPhotoIdNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d39b6e0a-f37c-44ad-aaf8-0ea7fef2e222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f4d05284-4b58-4da2-bfa0-685d3ce550c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-e7h1j6-tbPhotoIdNumber</value>
      <webElementGuid>f2756fcd-78b3-48b6-bfc2-531ee25b4d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e7h1j6-tbPhotoIdNumber</value>
      <webElementGuid>a4f663b6-372d-45be-9351-27f6a2b433c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88f88d94-c196-41f1-9b84-cd9319c8f3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>f4de77de-7c77-4801-9139-d2e188f6050e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>4260d08e-d216-42b3-ac6e-48f2eaa3d13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f6168b15-95fb-45e1-b74d-b03416e15276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[tbPhotoIdNumber]</value>
      <webElementGuid>4ededa3d-c3f3-4768-baa6-053bf2b2c867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cd92aab-5e62-4eb5-bde5-9cf27fedaeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a604dff9-37cc-4b84-a72b-4d4f53d67abd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e7h1j6-tbPhotoIdNumber&quot;)</value>
      <webElementGuid>d917ddaa-b166-4828-be5a-0ff5669456dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='e7h1j6-tbPhotoIdNumber']</value>
      <webElementGuid>8008fa00-64f4-47c5-a154-ddebfe4a9c28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e7h1j6']/div/input</value>
      <webElementGuid>29d7c340-ba98-498d-a1ee-83629f3180d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>c65f8180-ada4-437e-89de-c0330c94ef20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'e7h1j6-tbPhotoIdNumber' and @type = 'text' and @name = 'data[tbPhotoIdNumber]']</value>
      <webElementGuid>27758ce6-a89d-4979-b61d-e08a766eee08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
