<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Solo 401(k) Plan EIN_datasolo401KPlanEin</name>
   <tag></tag>
   <elementGuidId>61fdf478-46c7-4390-8d05-a488f1ffe374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='em6buc-solo401KPlanEin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#em6buc-solo401KPlanEin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6d73826-2247-4a82-8fab-fa0e8e3bfa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a2cac92-1d67-4a20-a3fd-a58ca786cde6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-em6buc-solo401KPlanEin</value>
      <webElementGuid>5d0de556-d556-4e37-b7dc-3f2edf9e6351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>em6buc-solo401KPlanEin</value>
      <webElementGuid>d136c9ad-eb09-4f8c-8bba-cd1a5900fc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d5662b8-d31f-4000-8eb8-f7d6e9dee76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>29a8cfb5-eaeb-4062-99b4-cd7d7e73d5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5a1a9e1d-e27c-416c-a8c4-2518b153c04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95469b11-befa-45fe-a857-071c37f6488d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[solo401KPlanEin]</value>
      <webElementGuid>1a927ced-4e77-4a4d-b6fb-125794f2eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e58df230-7304-43aa-86c4-4169fcfe8f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__-_______</value>
      <webElementGuid>f4ef7e65-a1d8-4360-bd5c-8a8ade775ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf0f2671-ac73-4a16-af4a-565358f581f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;em6buc-solo401KPlanEin&quot;)</value>
      <webElementGuid>2fa4713c-c027-478e-a250-f80a3db88f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='em6buc-solo401KPlanEin']</value>
      <webElementGuid>df566181-6ef8-42d5-9f8e-efbf84e890fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='em6buc']/div/input</value>
      <webElementGuid>7d517dda-c3ab-4991-90ca-f4b7cdbd30c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>248ecd05-ba85-40c3-8b43-ecad05b3353a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'em6buc-solo401KPlanEin' and @type = 'text' and @name = 'data[solo401KPlanEin]' and @placeholder = '__-_______']</value>
      <webElementGuid>e5172820-6432-420f-91e2-8d8b70bbf480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
