<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Photo Id Number_datatbPhotoIdNumber</name>
   <tag></tag>
   <elementGuidId>283846b7-0127-43df-bb5c-0309a196de63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='embwaiq-tbPhotoIdNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#embwaiq-tbPhotoIdNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>34c11e7d-fdbd-42a2-b20f-4161558479ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>87ce67bc-4bc5-4534-81e8-23b47615e5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-embwaiq-tbPhotoIdNumber</value>
      <webElementGuid>9c85ffd0-1cfa-42f2-aff6-847ad4a3ed9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>embwaiq-tbPhotoIdNumber</value>
      <webElementGuid>c87294ed-a34b-4750-8c20-0d0c9cab06d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d6bf1ec-5b5d-491d-b2b2-e171b1c37d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>ad77fc21-eb58-4cbb-93f3-41059a46f40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06f474cd-472b-4d48-a687-32b0e0034714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4f856651-a066-4522-98be-d5f9d407421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[tbPhotoIdNumber]</value>
      <webElementGuid>4a4e0869-736c-4f8f-b298-37f966bf7149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a540af9a-8bcc-42b2-b1d9-b21251aaca8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2eeed5cb-f8d5-4974-b41a-b781182407bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;embwaiq-tbPhotoIdNumber&quot;)</value>
      <webElementGuid>eeb998a6-6008-4f2e-8c19-0f7b1c719598</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='embwaiq-tbPhotoIdNumber']</value>
      <webElementGuid>470d2f07-4825-443a-a0a7-af58c499b33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='embwaiq']/div/input</value>
      <webElementGuid>89cc1ee6-997c-42c4-8e28-c0db1206e5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>d900249d-4989-40f8-8d2f-2b95f980a0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'embwaiq-tbPhotoIdNumber' and @type = 'text' and @name = 'data[tbPhotoIdNumber]']</value>
      <webElementGuid>74633054-4de4-46da-8f2b-1c018fc14108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
