<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_planSignerLastName_dataplanSignerLastName</name>
   <tag></tag>
   <elementGuidId>02c85a1e-99f4-4641-8236-ec84565e2729</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ex5d1xt-planSignerLastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ex5d1xt-planSignerLastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e536734-d62f-4a55-afb1-8ffd09fcfba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dc8a7308-57ac-482f-babc-5c9bee4b556a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-ex5d1xt-planSignerLastName</value>
      <webElementGuid>2cb5022d-952f-4788-82ef-9de2a1add236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ex5d1xt-planSignerLastName</value>
      <webElementGuid>2514c395-3deb-4c1d-9a2f-a6c0db7d4684</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c45ccacb-4682-4590-838d-df4eb0516ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>72948bbc-7568-411a-9e4f-2d82a3c83519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>2a5320ce-1d3b-4505-b550-ce85def42dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d12fe85b-733a-449f-b34a-f25a7545f921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[planSignerLastName]</value>
      <webElementGuid>45623536-2dd8-442c-8240-e335f269cdd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bb50d7c-7f39-42ab-bc29-2afd39149588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5ed0bbe4-9ff5-40fd-b250-32af84bc7ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ex5d1xt-planSignerLastName&quot;)</value>
      <webElementGuid>39470ab3-06f7-4cbe-8a62-e703e36b06c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ex5d1xt-planSignerLastName']</value>
      <webElementGuid>f5042f47-bc8b-46b9-948c-669fe3b6d4ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ex5d1xt']/div/input</value>
      <webElementGuid>8dbf5b0f-6a92-455b-8407-1e103b9ac661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>1c16bdf1-406f-4774-b4c1-a15a459d117d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ex5d1xt-planSignerLastName' and @type = 'text' and @name = 'data[planSignerLastName]']</value>
      <webElementGuid>9a8fb4de-b03e-46a0-a723-9c4ae1f4ab7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
