<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year_trusteeBirthDay-year</name>
   <tag></tag>
   <elementGuidId>bb601638-6b5e-4e15-b54b-bbab3b140408</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trusteeBirthDay-year']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trusteeBirthDay-year</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00f9f851-ce24-47ad-a612-6d5500d232d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3ba5cf92-bf6c-41a6-8d85-b75faecceea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-ezhccps-trusteeBirthDay</value>
      <webElementGuid>7e6ac9c4-4934-4dd1-ab26-cf3de179000d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2030</value>
      <webElementGuid>5bb3e6d8-4ed6-4498-8ac2-9b3545c31e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1900</value>
      <webElementGuid>9f706251-a8bc-4767-8cc8-5b6052a60b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0bff5dcb-241e-419b-ab88-593405711909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e1abde66-08ef-4707-b955-05ba45d7d58f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control formio-day-component-year</value>
      <webElementGuid>97ce75f7-681f-4f70-a532-828a789db752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trusteeBirthDay-year</value>
      <webElementGuid>088c1d14-34ac-4487-81ff-865d7904bd30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>year</value>
      <webElementGuid>5683af75-4f49-4092-a140-d1ecce06eceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ad03d0b-560d-463c-a346-5e739ef714bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trusteeBirthDay-year&quot;)</value>
      <webElementGuid>14d50b12-eaf7-4d57-b89a-78aa970c930d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trusteeBirthDay-year']</value>
      <webElementGuid>afa354e2-ed66-4dc9-9667-fef0b4a85b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ezhccps']/div/div[3]/div/input</value>
      <webElementGuid>467c8a47-f409-44be-9789-230765f3bade</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>2e7a3d0d-1f03-449b-9341-6443c963a5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'trusteeBirthDay-year']</value>
      <webElementGuid>2d02960c-e538-48b8-8106-4136a598ebdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
