<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_card-number-input  invalid dirty</name>
   <tag></tag>
   <elementGuidId>3bbec893-8b4a-4116-8600-10f4c027b3ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.card-number-input.invalid.dirty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e7bf895-5aa1-4f61-b5e0-6c35a2cdef95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2b171c27-0e8f-4c7a-9135-4ad39f1c4c70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-number-input  invalid dirty</value>
      <webElementGuid>4ee978f3-817f-4902-b7a8-65a6a421d073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Card number</value>
      <webElementGuid>647157ba-039f-4653-b8de-237f1ee105da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Card Number Input</value>
      <webElementGuid>df13bdff-6541-4819-b138-4c7e64771d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-placeholder</name>
      <type>Main</type>
      <value>Card number</value>
      <webElementGuid>009e7975-fe99-45ae-ba62-5282a62eef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fa6d9502-dc21-4c3e-bd50-10d86cc22290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>edd4544e-3d8e-41c4-a8ae-15f53ba0d327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react&quot;)/input[@class=&quot;card-number-input  invalid dirty&quot;]</value>
      <webElementGuid>b25af263-2002-4ade-a087-4152f4013b6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_/iframe_Payment Information_randomId40085802_196e19</value>
      <webElementGuid>2ba07b73-b2a5-4373-9c94-dc9242e254db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='4']</value>
      <webElementGuid>cab8adba-a0b0-4ec5-b600-13ff07cbe9f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='react']/input</value>
      <webElementGuid>7fa0419c-9edf-493a-b366-ae8dc1ccd1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2bff46e9-cdae-4d6e-80f0-d5292ef7efa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'Card number']</value>
      <webElementGuid>987420f7-2ada-4fe9-a008-ae8da5c0708f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
