<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trustee SuiteUnit Number_datatrusteeA_648f27</name>
   <tag></tag>
   <elementGuidId>a7b5e83a-3057-40d7-9f6f-f38b8a9b2b14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#evlrx8x-trusteeAddress02</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='evlrx8x-trusteeAddress02']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ca037bc-98b7-4ec9-b794-7b1db55764a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4f81f13e-3953-4ef7-8e9f-27aa0f0619a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-evlrx8x-trusteeAddress02</value>
      <webElementGuid>451895dc-3478-4a67-987f-98e73f5b4a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>evlrx8x-trusteeAddress02</value>
      <webElementGuid>3f226f1e-2a7f-46b4-860c-b1fd0803d186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>854cdd3e-b8ae-4422-b7e1-cfbc6542c672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>0a2ea105-d1a6-41ba-aefa-a1e7928a094a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c1dc9e1a-6217-4f1b-8797-849c8e36cf6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>21391800-0cf5-459d-b19f-d12d793a91d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[trusteeAddress02]</value>
      <webElementGuid>faab95ea-df05-41ff-9bb9-a1ca097155aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>32dcf1a7-23fd-4f8d-b73b-aaef726c3300</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c448d2c7-c968-4182-93be-ee28433c56d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;evlrx8x-trusteeAddress02&quot;)</value>
      <webElementGuid>a1943f90-256e-4173-96a2-7333c65d6b41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='evlrx8x-trusteeAddress02']</value>
      <webElementGuid>6befd065-6162-450e-973e-d5886e52cc4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='evlrx8x']/div/input</value>
      <webElementGuid>81bd0144-6c30-4f83-9e89-27fa2224de22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>5eb0bf57-6602-4a24-bd33-2688d0602a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'evlrx8x-trusteeAddress02' and @type = 'text' and @name = 'data[trusteeAddress02]']</value>
      <webElementGuid>f1ecd561-4e03-42a1-a876-d13be2f2ab18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
