<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Solo 401(k) Plan EIN_datasolo401KPlanEin</name>
   <tag></tag>
   <elementGuidId>61fdf478-46c7-4390-8d05-a488f1ffe374</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='euvw8xk-solo401KPlanEin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#euvw8xk-solo401KPlanEin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>367038de-52df-4790-8048-e1b975d21fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b356804a-6b82-43da-8b4c-3ba52668b8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>l-euvw8xk-solo401KPlanEin</value>
      <webElementGuid>3db0da47-52fe-4365-a931-aff9bf821314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>euvw8xk-solo401KPlanEin</value>
      <webElementGuid>3d710bc8-939b-473d-bcd7-4385e2205ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>436462c3-62d9-41b3-b862-87f9f24ca863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>cda49f9d-50d0-423f-83a1-752b09da30fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>86b2faff-1545-4b0d-ba83-8af36581394a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e167ed-9e8e-4298-807e-33525e474fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[solo401KPlanEin]</value>
      <webElementGuid>ee287633-bb0b-499a-8307-8f4f3cb6771d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81e9f5b8-2e45-4457-bffa-c07ac40bfdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>__-_______</value>
      <webElementGuid>1b4fed63-593e-458a-a7fe-0038be413043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>977eaa8e-1801-4dc0-8d90-2fa6d7676685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;euvw8xk-solo401KPlanEin&quot;)</value>
      <webElementGuid>c7334d32-f624-4d8c-bf6b-ddcc215a64ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='euvw8xk-solo401KPlanEin']</value>
      <webElementGuid>dec8f855-9671-4131-bbd9-aa211ac9167d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='euvw8xk']/div/input</value>
      <webElementGuid>493374fc-3436-4a30-909f-8bf1601ef2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>fde0e52c-8fa6-442b-b62a-b5437f0a5890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'euvw8xk-solo401KPlanEin' and @type = 'text' and @name = 'data[solo401KPlanEin]' and @placeholder = '__-_______']</value>
      <webElementGuid>511f8b00-5faf-4b0b-b248-f69093e86a33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
