<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_spanBank transfer from another accou_2401b4</name>
   <tag></tag>
   <elementGuidId>d016be28-e4e9-4198-933d-9e15d275dc46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='e5zh5h-tbTrustSourceOfFunds']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e5zh5h-tbTrustSourceOfFunds</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1afd8267-c363-447c-bcdd-1cc0170f8385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2be6c6a-7a1e-4937-b528-58652b6598b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e5zh5h-tbTrustSourceOfFunds</value>
      <webElementGuid>cf23c606-f243-40a4-bb28-000b5cf6e426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>1a662b92-e350-45e3-84dd-5ce0a2775013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>831778d6-0ddf-4f45-877b-a5edf128facf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c9871ca-0f82-4f64-a69b-c922dd2dd8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[tbTrustSourceOfFunds]</value>
      <webElementGuid>e85e0a36-f4ec-453d-b991-6507179b3b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>5112d72a-779c-4c5d-aaaa-2f327bc7c29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>ff68850d-706e-4035-b76d-09f6461f994b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>732d5dd5-dcfb-43dd-afa8-544c94065317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>188dd376-3471-45df-b653-6f87a190a150</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>Bank transfer from another account you own&lt;/span></value>
      <webElementGuid>09201530-ea98-4914-a6d5-2c2d04706aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e5zh5h-tbTrustSourceOfFunds&quot;)</value>
      <webElementGuid>a38f121f-8992-4d17-b352-7e6d81e266fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e5zh5h-tbTrustSourceOfFunds']</value>
      <webElementGuid>33225764-e702-4f83-97c5-ce53020392ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e5zh5h']/div/div/select</value>
      <webElementGuid>6bae15db-6d12-4e34-820f-69fdf99ac56f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB_trustSourceOfFunds'])[1]/following::select[1]</value>
      <webElementGuid>444a6bba-b517-4e93-af82-55ff804d1322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::select[1]</value>
      <webElementGuid>257adb16-e7cc-4288-8193-26795830e171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bank transfer from another account you own'])[1]/preceding::select[1]</value>
      <webElementGuid>04034537-fac5-4a81-8490-1567189cd64c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[4]/preceding::select[1]</value>
      <webElementGuid>d3d86bd8-b10d-4657-8f67-ade3e54c2dcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>7a085a39-e2c9-4d24-b2bc-172d03872461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e5zh5h-tbTrustSourceOfFunds' and @type = 'text' and @name = 'data[tbTrustSourceOfFunds]' and (text() = '&lt;span>Bank transfer from another account you own&lt;/span>' or . = '&lt;span>Bank transfer from another account you own&lt;/span>')]</value>
      <webElementGuid>aa2f2194-e55f-4765-bc22-a9b6de8014f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
