<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Title_datatrusteeTitle</name>
   <tag></tag>
   <elementGuidId>53173122-2b62-4ed5-b340-f8f6d9706a2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#edgpjn5-trusteeTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Title')]/following-sibling::div//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>99f677ff-885b-411b-a864-cbaddb402c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>655d704b-69dd-4664-b41c-3a61ecf60e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>edgpjn5-trusteeTitle</value>
      <webElementGuid>78687472-9d11-4e09-9e6d-cbb31cca6274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>5d6f7d78-bf28-4834-894e-697c4f2abaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>6e135659-83fc-4546-856a-274ce82b78bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>59356eb7-f061-4fb2-817b-35211004f3c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[trusteeTitle]</value>
      <webElementGuid>30178fdd-c75d-437a-83db-639f4e96aef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>9ce815b2-ece6-4138-b866-e79b32e34bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>daabfa83-c9b8-4a3a-b70e-cac873646d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ad7a3573-3a7b-4e7f-b544-205b63bd6349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>27a8a15c-bf1f-4383-9f50-cfb4d4eaba33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;edgpjn5-trusteeTitle&quot;)</value>
      <webElementGuid>31c439f7-681c-463c-932e-5fba853a714a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='edgpjn5-trusteeTitle']</value>
      <webElementGuid>1f584fa0-0b7e-45ea-abab-f4c2b7be06b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='edgpjn5']/div/div/select</value>
      <webElementGuid>ee766ab7-5ab3-4da7-91ab-9ba890169bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7a28670c-969a-4e64-b890-bd1429d3922f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'edgpjn5-trusteeTitle' and @type = 'text' and @name = 'data[trusteeTitle]']</value>
      <webElementGuid>7a677b32-2e0e-45cd-995e-77e14c94ea61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
