<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_span0-25,000span</name>
   <tag></tag>
   <elementGuidId>43e92575-c19b-458c-b33f-1839a19aac86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='e08qq5h-tbTrustAccountMonthlyActivityDomestic']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e08qq5h-tbTrustAccountMonthlyActivityDomestic</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>474fc85c-48cd-475d-ac7d-2426afa534b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1a33effc-12f2-4565-b0ef-db2fd13bec62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e08qq5h-tbTrustAccountMonthlyActivityDomestic</value>
      <webElementGuid>88e218b0-4ec9-46ab-83e7-1d3600f8580d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>e23a97ca-66e5-4f9e-b4de-14ecec7bace5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>2161afce-6fc0-44f1-9e49-cf18d7a12a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7691749-3b0c-48c4-afd7-c78726c01208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[tbTrustAccountMonthlyActivityDomestic]</value>
      <webElementGuid>18725700-41ec-4f4f-aaf4-d1d721452e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>e4c5b0dc-b2e8-4b28-ab8b-e954c35b727f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>f48b7204-b7a3-4e01-96da-f5496067b253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c4a659be-915f-40fc-84ad-d2b68bdaab6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>9766d257-9204-430e-ba63-a765a25a3b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>$0-$25,000&lt;/span></value>
      <webElementGuid>1848c7a6-aaf0-44bc-bcad-0eaefab2c339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e08qq5h-tbTrustAccountMonthlyActivityDomestic&quot;)</value>
      <webElementGuid>e7e2abd0-aa7b-42df-af5f-bfef379cb38c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e08qq5h-tbTrustAccountMonthlyActivityDomestic']</value>
      <webElementGuid>1e690635-e9c3-4ae7-8f4f-42fc3ae01ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e08qq5h']/div/div/select</value>
      <webElementGuid>1dbca3d5-19b6-4038-b6f1-13cde2aceb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB_trustAccountMonthlyActivityDomestic'])[1]/following::select[1]</value>
      <webElementGuid>207ea91f-3546-439d-ac5a-d0a78dc6324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', numeric only,'])[1]/following::select[1]</value>
      <webElementGuid>f9584593-2a12-42cd-94ca-4ba65886736e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0-$25,000'])[1]/preceding::select[1]</value>
      <webElementGuid>a86fb370-7b59-4bf4-a748-f24e0e48eaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::select[1]</value>
      <webElementGuid>f8eafebf-fc80-43cb-982a-0d44eb3df3a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>affe9f31-c0e3-4484-84c5-6e194677372b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e08qq5h-tbTrustAccountMonthlyActivityDomestic' and @type = 'text' and @name = 'data[tbTrustAccountMonthlyActivityDomestic]' and (text() = '&lt;span>$0-$25,000&lt;/span>' or . = '&lt;span>$0-$25,000&lt;/span>')]</value>
      <webElementGuid>d54e27d9-769a-45d7-a141-0b7a69bbcca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
