<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_spanDr.span</name>
   <tag></tag>
   <elementGuidId>bce51d72-87f1-426a-b066-470ed41a8d94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#e0eers8-trusteeTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='e0eers8-trusteeTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b34f82a5-3271-4c27-bd85-eab7b44eaefd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2024230-a468-44bf-8e8c-c8d2fb956e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e0eers8-trusteeTitle</value>
      <webElementGuid>61206fd5-dfa7-4ae2-8f45-590a1ff69384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>cc79d9e2-304d-490d-8e4e-d85d5bb5964e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>6311c8d2-f1b7-40e6-9650-3be11be9e7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>812540ca-889f-4b74-9a11-62d015b42538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[trusteeTitle]</value>
      <webElementGuid>8d5a1e95-8ac3-46e6-8548-1b87e9c95d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>65470daf-21ab-43a8-b0ba-2cc6f924d42b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>ecad74fd-bbe4-4f30-80a6-cbd5cea2f5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b46c3eb-1c8d-486c-bf3b-98e24adf6a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>84876842-121e-4a16-9edc-0ed1128d09c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>Dr.&lt;/span></value>
      <webElementGuid>22463376-f613-4f6e-b684-e920ed5f8436</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e0eers8-trusteeTitle&quot;)</value>
      <webElementGuid>72415caf-9613-4c9d-8055-42088c39a687</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e0eers8-trusteeTitle']</value>
      <webElementGuid>51d549aa-49dd-4378-8d01-a417fdca9c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e0eers8']/div/div/select</value>
      <webElementGuid>afa16e26-44d0-429a-aa68-cbe26d523c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::select[1]</value>
      <webElementGuid>003cacd1-2307-4321-b163-628f9321a7d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Before Submitting'])[1]/following::select[1]</value>
      <webElementGuid>39b716eb-76f5-45ec-b147-f3cf3e65b103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dr.'])[1]/preceding::select[1]</value>
      <webElementGuid>cee78a26-4aad-49ca-a7c6-faa5051df864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::select[1]</value>
      <webElementGuid>83d9c419-26ed-4755-b0b4-4712ca05b682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3bb15e58-d2f6-4a41-97c1-4f6b7bf0b4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e0eers8-trusteeTitle' and @type = 'text' and @name = 'data[trusteeTitle]' and (text() = '&lt;span>Dr.&lt;/span>' or . = '&lt;span>Dr.&lt;/span>')]</value>
      <webElementGuid>532e7bd7-b39d-4854-a059-1e43c5d350d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
