<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_span2021 Tax Yearspan</name>
   <tag></tag>
   <elementGuidId>b859d8f4-df4f-4ba8-97af-49b9213d818b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Tax Year Plan is Established')]/following-sibling::div//span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e0228gg-planEstablishDate</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'e2lqyq-planEstablishDate' and @type = 'text' and @name = 'data[planEstablishDate]' and (text() = '&lt;span>2021 Tax Year&lt;/span>' or . = '&lt;span>2021 Tax Year&lt;/span>')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2aa28554-5d10-48af-b69e-9cbba9cdba5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7896eee6-17eb-44aa-ab09-c560ac96754f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>e0228gg-planEstablishDate</value>
      <webElementGuid>18beed3d-70c0-4a27-9213-3c71126738d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>a1d87649-4084-41e9-9544-b88e553344a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>f2ac441a-e15b-41ea-bb64-0c92d2974b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c2113da-6f6c-4e18-b07e-8a11cb86fdd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[planEstablishDate]</value>
      <webElementGuid>a72fe3f3-8148-45be-8995-6c9463f0e66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>a22ab332-889f-4c84-8dc4-eb49b04d56e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>088c0095-b892-4d18-9d30-689626b5d193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2e5bc274-fbe8-4f37-a6cc-9ca8f577c249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>65143f62-0678-4004-bd11-4c7691c1a7fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>2021 Tax Year&lt;/span></value>
      <webElementGuid>4e63eeff-7160-4e14-bced-79ee1af5f8ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e0228gg-planEstablishDate&quot;)</value>
      <webElementGuid>8018343f-a7a0-4870-8240-c50e303b2114</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='e0228gg-planEstablishDate']</value>
      <webElementGuid>59727a83-4dc1-4ea6-8ef9-1aa931f15831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e0228gg']/div/div/select</value>
      <webElementGuid>a07cc624-1f2e-43a7-9d7b-8f27778d2a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax Year Plan is Established'])[1]/following::select[1]</value>
      <webElementGuid>bcc01194-d573-4c05-861a-05ae70141e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Before Submitting'])[1]/following::select[1]</value>
      <webElementGuid>8f4047e2-ec4f-4f86-b8b8-d96d135348a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::select[1]</value>
      <webElementGuid>79d81ccf-815f-4e24-a95c-629942d5b2f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solo 401(k) Plan EIN'])[1]/preceding::select[1]</value>
      <webElementGuid>c7a5f2ea-de78-48dc-b25c-bfaaf0b8f3ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>749f4df1-c89b-4301-8875-4202906f3115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'e0228gg-planEstablishDate' and @type = 'text' and @name = 'data[planEstablishDate]' and (text() = '&lt;span>2021 Tax Year&lt;/span>' or . = '&lt;span>2021 Tax Year&lt;/span>')]</value>
      <webElementGuid>b42f3f97-0689-4f3e-a5a2-b409987466ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
