<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_span2022 Tax Yearspan</name>
   <tag></tag>
   <elementGuidId>e3b1c4fb-275f-4c59-ba37-b080e9e6271c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ez4nke-planEstablishDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[contains(text(),'Tax Year Plan is Established')]/following-sibling::div//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a27384c1-6cf2-4558-a8ec-666c4a44fd4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f91e90f0-8e1c-4e4c-8bab-f8e4b8cad579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ez4nke-planEstablishDate</value>
      <webElementGuid>a3b9cc1f-e10f-4c76-9f72-c077749f3ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>bedb5318-f73b-4be5-ba17-bef07ebce0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>c64ef3b1-08f1-42b0-ae5e-d51ed0c8cae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c467a77a-44a7-4e32-9d5a-8229774cbaee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[planEstablishDate]</value>
      <webElementGuid>86085562-7def-40bb-8700-01dabf140432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>3d398ae5-88fa-41b7-a513-6ba57190f867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>b46eebfa-a800-41f8-be89-d203313b0900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>43a156b4-5c7e-4d73-82ab-0ee7540e0780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>da9be0de-8058-4535-916b-a7116de6b812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>2022 Tax Year&lt;/span></value>
      <webElementGuid>826467b0-6a72-4b9b-909a-96df5d1c1697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ez4nke-planEstablishDate&quot;)</value>
      <webElementGuid>10323e70-30ce-4bf8-baff-ca78667d29b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ez4nke-planEstablishDate']</value>
      <webElementGuid>7de8b006-baa9-4c9d-bce1-1fbc9a3b4d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ez4nke']/div/div/select</value>
      <webElementGuid>b372d9a5-3db7-428a-bdb4-a04e2288d1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tax Year Plan is Established'])[1]/following::select[1]</value>
      <webElementGuid>9089cf5f-2b1b-42fc-93fe-81cb9183941b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Before Submitting'])[1]/following::select[1]</value>
      <webElementGuid>7ca4db5f-2019-4969-b578-79e9b8c27674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::select[1]</value>
      <webElementGuid>cfcda4d7-14fd-4f36-b0a8-cb074fbc642e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solo 401(k) Plan EIN'])[1]/preceding::select[1]</value>
      <webElementGuid>bffd4249-c16c-43ba-9f39-2ea023f83a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>5c6f767e-c734-43fc-b6e7-54769d604b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ez4nke-planEstablishDate' and @type = 'text' and @name = 'data[planEstablishDate]' and (text() = '&lt;span>2022 Tax Year&lt;/span>' or . = '&lt;span>2022 Tax Year&lt;/span>')]</value>
      <webElementGuid>a6ea6248-ddad-4f2a-beeb-ba45ef7b5f35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
