<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_span0-25,000span_1</name>
   <tag></tag>
   <elementGuidId>fefaeea6-7852-4ec5-8b8f-50755f59d302</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='eahvsq9-tbTrustAccountMonthlyActivityInternational']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eahvsq9-tbTrustAccountMonthlyActivityInternational</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8e934e5c-d989-4350-95c1-a2135bd2f45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>69aa8166-12df-4cce-b72b-a1a26daade8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eahvsq9-tbTrustAccountMonthlyActivityInternational</value>
      <webElementGuid>43ecdc3d-e86d-43dd-adc0-79ea8509ae9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>85094da2-4e9d-421c-8613-a338880cf4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control choices__input</value>
      <webElementGuid>2f1ab69e-ca7d-48c3-92d6-d51daffc9690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86606269-6e13-42c4-b7a7-a7d566448c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data[tbTrustAccountMonthlyActivityInternational]</value>
      <webElementGuid>ea708e28-700f-4fa7-b67c-996ff3390fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref</name>
      <type>Main</type>
      <value>selectContainer</value>
      <webElementGuid>e37f08ff-eed8-418e-b1ff-acf274e00094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>9ff3d29f-147b-4ac4-8266-9b16d44e89fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>89a1632d-701b-43cd-a48e-1db04cbdc955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-choice</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>69bacc69-0a36-4af7-be60-9f43de8f64dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;span>$0-$25,000&lt;/span></value>
      <webElementGuid>dd7b6105-1ee9-44f8-b80a-95930df9af6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eahvsq9-tbTrustAccountMonthlyActivityInternational&quot;)</value>
      <webElementGuid>0b415a38-9884-495e-af28-074bf457562f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='eahvsq9-tbTrustAccountMonthlyActivityInternational']</value>
      <webElementGuid>a4765e1e-4359-4308-a1c1-ae2509cf0d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eahvsq9']/div/div/select</value>
      <webElementGuid>392292e0-daa2-4d43-95bf-d8627530215b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TB_trustAccountMonthlyActivityInternational'])[1]/following::select[1]</value>
      <webElementGuid>07a870a3-42d6-4dd5-a969-a6c3240bb6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Greater than $1,000,000'])[1]/following::select[1]</value>
      <webElementGuid>e3a1c2cf-d004-4872-884a-a4d10e0a9073</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0-$25,000'])[3]/preceding::select[1]</value>
      <webElementGuid>9039799f-0b98-466b-8049-86340286016c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[2]/preceding::select[1]</value>
      <webElementGuid>00bfbf09-e4c2-4cd0-94bd-d5d478dab23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/select</value>
      <webElementGuid>90685563-bf73-4af2-a8e2-752e0bc743df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'eahvsq9-tbTrustAccountMonthlyActivityInternational' and @type = 'text' and @name = 'data[tbTrustAccountMonthlyActivityInternational]' and (text() = '&lt;span>$0-$25,000&lt;/span>' or . = '&lt;span>$0-$25,000&lt;/span>')]</value>
      <webElementGuid>c4f9f342-4407-43bf-b5c3-69f737fb7dcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
