<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pricing</name>
   <tag></tag>
   <elementGuidId>a2784e63-92c5-44a0-a18e-a6c278538a6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>84a7a970-82f1-47e8-a20c-ff35eacbbae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center px-3 py-2 text-lg font-medium outline-app-theme-500 text-gray-900 no-underline focus:ring-2 active:ring-app-theme-500 focus:ring-app-theme-500 hover:outline-app-theme-500</value>
      <webElementGuid>5e980541-6f0b-47a4-a441-46c6dc356eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/pricing</value>
      <webElementGuid>9868b430-d56e-437f-8051-d2894de2142b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pricing</value>
      <webElementGuid>05c9ec01-0042-4620-940f-d90fa0926c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gatsby-focus-wrapper&quot;)/div[@class=&quot;z-30 w-full&quot;]/nav[@class=&quot;max-w-[1682px] bg-white px-6 mx-auto flex items-center justify-between relative z-50 py-3 md:py-8&quot;]/div[@class=&quot;hidden large:flex items-center justify-between gap-4 xl:gap-8&quot;]/div[@class=&quot;flex items-center justify-between gap-2 xl:gap-8&quot;]/div[@class=&quot;flex items-center relative group&quot;]/a[@class=&quot;inline-flex items-center px-3 py-2 text-lg font-medium outline-app-theme-500 text-gray-900 no-underline focus:ring-2 active:ring-app-theme-500 focus:ring-app-theme-500 hover:outline-app-theme-500&quot;]</value>
      <webElementGuid>119b9f0e-0d41-4158-be6b-f53b40c94e31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gatsby-focus-wrapper']/div/nav/div/div/div[5]/a</value>
      <webElementGuid>d1a03281-98b4-4924-814f-f7e9a3c0cecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pricing')]</value>
      <webElementGuid>eadd2e8e-56b1-4a74-b17d-d537ece31f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Advantages of the SEPIRAk Recordkeeping System'])[1]/following::a[1]</value>
      <webElementGuid>33b4830d-c8a1-4c5f-abbe-b2d262d0528e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Benefits of a Solo 401(k) plan'])[1]/following::a[2]</value>
      <webElementGuid>76587e76-081b-408c-9ab7-e9e3da12c4f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/preceding::a[1]</value>
      <webElementGuid>6501b2a4-c0a4-4ca3-a3b9-b853360a3618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pricing']/parent::*</value>
      <webElementGuid>6367a413-64c9-40dd-a007-315b76bc7129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/pricing')]</value>
      <webElementGuid>c1e11a53-9f63-4b72-873a-81638637c260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>2ce936d9-e168-49b7-a958-694e2e5d33fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/pricing' and (text() = 'Pricing' or . = 'Pricing')]</value>
      <webElementGuid>cb4f6670-edcd-4cb0-953b-82b5802c8608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
