<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Please select the state in which the ID was issued</name>
   <tag></tag>
   <elementGuidId>5fea7b61-1db6-4a8e-88c8-5e1d7dc7c3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tippy-32']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tippy-32 > div.tippy-box > div.tippy-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b603ac23-1510-4639-ab37-feba7c365140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tippy-content</value>
      <webElementGuid>82b3d8f9-ec91-4bab-9703-7b9bd1290152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>visible</value>
      <webElementGuid>b81ca654-71e5-4deb-8c30-b6a0073ffdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please select the state in which the ID was issued.</value>
      <webElementGuid>1fee9076-8c66-4220-81b1-50675ba2180b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tippy-32&quot;)/div[@class=&quot;tippy-box&quot;]/div[@class=&quot;tippy-content&quot;]</value>
      <webElementGuid>cf72a35e-629a-4d15-9a1b-59e84c555cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tippy-32']/div/div</value>
      <webElementGuid>5a9f1379-bad7-4563-aeed-db928f8e0d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the state in which the ID was issued.'])[2]/following::div[4]</value>
      <webElementGuid>89235aa2-f175-431e-882a-3522095c19dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please select the state in which the ID was issued.'])[1]/following::div[8]</value>
      <webElementGuid>d679008c-bc92-4e71-b53a-46688d8c148e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[1]/preceding::div[2]</value>
      <webElementGuid>534c46d4-bd82-4444-9ea7-16db71b4ab44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::div[2]</value>
      <webElementGuid>3b2e6144-28eb-4b32-ab7c-49a0ae95ea39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div[3]/div/div</value>
      <webElementGuid>1c561b8c-7a03-4fcc-a879-d8d9c006ffb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Please select the state in which the ID was issued.' or . = 'Please select the state in which the ID was issued.')]</value>
      <webElementGuid>c0db2f14-a937-4f84-a11d-6e8747a2b0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
