<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dr</name>
   <tag></tag>
   <elementGuidId>2caaf114-7784-4bf9-ac81-d37cdf115ccb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='choices--eiwzws-trusteeTitle-item-choice-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#choices--eiwzws-trusteeTitle-item-choice-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ffcaba26-b9af-472d-8c38-63f857c5d055</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--eiwzws-trusteeTitle-item-choice-3</value>
      <webElementGuid>6f1c64ed-3a81-44cf-a882-c0e83a5fe520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--choice choices__item--selectable is-highlighted</value>
      <webElementGuid>faedfdfa-14c0-47d0-8a8f-0ace0e540f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>95571983-1604-4e73-be30-09cd7f95d176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f5e224ce-f7cf-43c1-a09a-261779892f3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Dr</value>
      <webElementGuid>e92c3bb9-c0ce-4e34-9356-2a1735a08aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e4c30ccc-e880-4b36-936d-6b88ddc95eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dr.</value>
      <webElementGuid>d6b8e17d-e9d2-4006-aa4c-adbf22495fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--eiwzws-trusteeTitle-item-choice-3&quot;)</value>
      <webElementGuid>5255dc79-95fa-4066-9755-f8eda99a0bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--eiwzws-trusteeTitle-item-choice-3']</value>
      <webElementGuid>ef6abdce-e6da-4243-a452-9dc61f356014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eiwzws']/div/div[2]/div/div[3]</value>
      <webElementGuid>6bceab8b-70a6-4cd0-a923-1cc24a1f5f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ms.'])[2]/following::div[1]</value>
      <webElementGuid>282d14a0-a82c-4c3c-913d-c28cd06cab57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mrs.'])[1]/following::div[2]</value>
      <webElementGuid>b85f6f72-9116-4644-a7cb-9acf58e68685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mr.'])[1]/preceding::div[1]</value>
      <webElementGuid>53fd4229-8fe2-43f3-8714-f01e4add5140</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[3]</value>
      <webElementGuid>4d8bb7b7-7808-4ee8-9d4a-cc5f6a1a2aad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--eiwzws-trusteeTitle-item-choice-3' and (text() = 'Dr.' or . = 'Dr.')]</value>
      <webElementGuid>934c02f9-aa4c-485b-b566-d9ca0942e441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
