<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AlabamaRemove item</name>
   <tag></tag>
   <elementGuidId>18a59e93-15eb-479e-8fa1-4bf51dbc40a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e2543hl']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.choices__list.choices__list--single > div.choices__item.choices__item--selectable</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d372a46d-c219-44fb-b435-159fd7b1f605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--selectable</value>
      <webElementGuid>4207ae28-9cd0-4899-93ac-a7458807b702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>482b2c78-b288-40b5-b444-7a2a5359768a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Alabama</value>
      <webElementGuid>96027e5b-417b-4bb5-8df2-6647ce84e8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21880fa7-95d1-4cf5-8f30-c4f8c758397d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AlabamaRemove item</value>
      <webElementGuid>e2f9d35a-e1eb-4c8c-9c1f-6065f1eedfea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2543hl&quot;)/div[@class=&quot;choices form-group formio-choices is-open is-focused&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]/div[@class=&quot;choices__list choices__list--single&quot;]/div[@class=&quot;choices__item choices__item--selectable&quot;]</value>
      <webElementGuid>2da17dca-6c16-4fc7-b43a-6a10ba6b7803</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2543hl']/div/div/div/div</value>
      <webElementGuid>3ec86741-bda3-4b67-b015-768811e6d180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Issued'])[1]/following::div[4]</value>
      <webElementGuid>a72b9c03-eb5b-4cfc-a192-d7a82657d697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Id Number'])[1]/following::div[8]</value>
      <webElementGuid>a4a8d506-f6f5-4cf9-9d65-09d365604117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div/div/div</value>
      <webElementGuid>9dedb88b-9f89-46a8-83a7-f268d3812135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AlabamaRemove item' or . = 'AlabamaRemove item')]</value>
      <webElementGuid>0ad6e2ce-8227-43c7-acda-7a559864d119</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
