<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Alabama</name>
   <tag></tag>
   <elementGuidId>c34f5934-ee3c-4047-afc4-bd23c4686e75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='choices--e2543hl-tbIdState-item-choice-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#choices--e2543hl-tbIdState-item-choice-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>26f78667-00bb-4062-a3e3-dea7becd9c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--e2543hl-tbIdState-item-choice-1</value>
      <webElementGuid>554e584b-5a88-43ad-9b98-198775e68d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--choice choices__item--selectable is-highlighted</value>
      <webElementGuid>fb42db61-4e07-4da0-932f-5165260fbf64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>7d1cccb9-9ce6-4cfe-98d1-b074ebf0df64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>13229df3-cc3a-4c16-8d58-e3fe629c5286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Alabama</value>
      <webElementGuid>f842ccb8-9384-4354-8751-94dfa2f54de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d4ce556-7f84-4ee1-b495-d8eae1a936ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alabama</value>
      <webElementGuid>234b436d-e76f-469d-9e9c-3cb6e5b671f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--e2543hl-tbIdState-item-choice-1&quot;)</value>
      <webElementGuid>feed1365-c76b-468c-98c8-e4ee18338541</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--e2543hl-tbIdState-item-choice-1']</value>
      <webElementGuid>88b93dad-f41d-451c-9f24-99f0db625011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2543hl']/div/div[2]/div/div</value>
      <webElementGuid>e79a211c-b488-44f6-8ecb-a949554b6b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Issued'])[1]/following::div[6]</value>
      <webElementGuid>496127e7-f7cd-4f46-9096-113db074599b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Id Number'])[1]/following::div[10]</value>
      <webElementGuid>83fd3881-3669-4510-be83-086080fece85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alaska'])[1]/preceding::div[1]</value>
      <webElementGuid>5cea39f4-c781-42dc-8606-64971d0fdf18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/div[2]/div/div</value>
      <webElementGuid>49908050-7b16-45e6-b97c-664f73d65a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--e2543hl-tbIdState-item-choice-1' and (text() = 'Alabama' or . = 'Alabama')]</value>
      <webElementGuid>dbf64ceb-8f57-43ca-b049-c70d7f70e703</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
