<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Alabama</name>
   <tag></tag>
   <elementGuidId>aa6f4188-e69d-4c50-9bff-0dff49d01ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='e2543hl']/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.choices__list.choices__list--single > div.choices__item.choices__item--selectable > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0c0d7a47-efbd-4942-8957-6ffd7c431fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alabama</value>
      <webElementGuid>c56a474d-dffa-4b1f-a272-6d1a1a044979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e2543hl&quot;)/div[@class=&quot;choices form-group formio-choices is-open is-focused&quot;]/div[@class=&quot;form-control ui fluid selection dropdown&quot;]/div[@class=&quot;choices__list choices__list--single&quot;]/div[@class=&quot;choices__item choices__item--selectable&quot;]/span[1]</value>
      <webElementGuid>0527f949-9bd3-493d-9fad-f393a9bec88b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e2543hl']/div/div/div/div/span</value>
      <webElementGuid>79fc4f5b-49a9-448c-96a3-5ce5cbe28d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State Issued'])[1]/following::span[1]</value>
      <webElementGuid>3ac56fc0-061c-4486-9eb6-c652ae0e88e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photo Id Number'])[1]/following::span[1]</value>
      <webElementGuid>8c7e82d3-d288-451e-be90-2e0f699037c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove item'])[1]/preceding::span[1]</value>
      <webElementGuid>65ea459d-0403-43c7-baeb-92e9cd8888b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alabama'])[2]/preceding::span[1]</value>
      <webElementGuid>28f11c6f-391b-48f9-acd3-2882ec1a87fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alabama']/parent::*</value>
      <webElementGuid>5f51a374-b00a-47b0-b00a-b7439edbe152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/span</value>
      <webElementGuid>08ed958f-a3db-41c3-b154-77054f128730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Alabama' or . = 'Alabama')]</value>
      <webElementGuid>194799c2-af52-4992-95b3-cd91501d1e3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
